a. Импортируйте библиотеку NumPy

---

In [3]:
import numpy as np
print ('Numpy импортирована')

Numpy импортирована


b. Создайте массив из 10 нулей

---

In [5]:
array = np.zeros(10)
print (array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


c. Создать массив из 10 единиц

---


In [6]:
array = np.ones(10)
print (array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


d. Создать массив из 10 пятерок

---


In [7]:
array = np.ones(10)*5
print (array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


e. Создать массив из целых чисел от 10 до 50

---



In [8]:
array = np.arange(10,51)
print (array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


f. Создать массив из четных чисел от 10 до 50

---



In [9]:
array = np.arange(10,51,2)
print (array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


g. Создать матрицу 3х3 с числами от 0 до 8

---



In [10]:
matrix = np.arange(0,9).reshape(3,3)
print (matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


h. Создать единичную матрицу 3x3

---



In [11]:
matrix =np.eye(3,3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


i. Используйте NumPy для генерации случайного числа от 0 до 1

---



In [13]:
rndm_num = np.random.rand(1)
print ('Случайное число:', rndm_num)

Случайное число: [0.35707116]


j. Используйте NumPy для генерации массива из 25 случайных чисел,
взятых из стандартного нормального распределения

---



In [14]:
array = np.random.rand(25)
print (array)

[0.82436196 0.67220651 0.91861591 0.76310806 0.10026631 0.70907757
 0.06114842 0.83774929 0.39824641 0.28354617 0.63956704 0.51701588
 0.43308818 0.37861614 0.95323201 0.25074751 0.90130486 0.6444752
 0.17607323 0.15314375 0.58856075 0.24955492 0.27750467 0.66234521
 0.31560654]


k. Создайте матрицу по обарзцу, используя функции библиотеки NumPy

---



In [15]:
matrix = np.arange(0.01, 1.01, 0.01).reshape(10,10)
print (matrix)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


l. Дана стартовая матрица Вывести матрицу по образцу из задания

---



In [16]:
#стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [17]:
array = mat[2:,1:]
print ('array', array)

array [[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


m. Написать код обращения к элементу который вернет значение 20 из
стартовой матрицы задачи l.

---



In [18]:
element = mat[mat == 20]
print(element)

[20]


n. Написать код к стартовой матрице, который воспроизводит
вывод по образцу из задания

---



In [19]:
array = mat[:3,1].reshape(3,1)
print ('array', array)

array [[ 2]
 [ 7]
 [12]]


o. Написать код к стартовой матрице, который воспроизводит вывод по образцу из задания

---



In [20]:
array = mat[4:]
print ('array', array)

array [[21 22 23 24 25]]


p. Написать код к стартовой матрице, который воспроизводит вывод по образцу из задания

---



In [21]:
array = mat[3:]
print ('array', array)

array [[16 17 18 19 20]
 [21 22 23 24 25]]


q. Получить сумму всех значений в стартовой матрице mat

---



In [22]:
print ('Сумма элементов стартовой матрицы:', mat.sum())

Сумма элементов стартовой матрицы: 325


r. Получить стандартное отклонение в стартовой матрице mat

---



In [23]:
print ('Стандартное отклонение в стартовой матрице:', mat.std())

Стандартное отклонение в стартовой матрице: 7.211102550927978


s. Получить сумму значений в колонках в стартовой матрице mat

---



In [24]:
print (mat.sum(axis=0))

[55 60 65 70 75]
